### ISSUE TITLE
Time access to particular problems

### ISSUE THREAD

**Issue by Paulie14** [code-critic/cc.net#2]
How to set time access "problem enabled/visible from - until"

- Found key `avail` in course template, not sure exactly what will happen after that time (I will test..)
- We talked about key `since` I remember, but not sure.

My ideas:
- the main motive is to motivate students to do the problems in time
- I would differentiate between visible/enabled - if too complicated, then all problems can be visible from the beginning and just set "enabled from-until"
- I do not mind all the problems to be visible/enabled from the beginning
- after the end time, I would like the test to be "gray", but still accessible to see the instructions.. However submission button would be disabled
(I can still postpone the end time, if the students come to me begging on their knees :) )
- even without this, I can sort the submitted results by time, so I know who made it in time - it might be sufficient eventually, but can become s pain in case of more students and problems..
- all this is for discussion

**Comment by janhybs** [comment]
Both fields `since` and `avail` are optional. If set, will limit the visibility of a problem for a student.

Semitransparent course means the students will not be seeing this course:
![image](https://user-images.githubusercontent.com/894428/94992299-63536400-0589-11eb-94b8-8225e15c399b.png)

Student will see:
![image](https://user-images.githubusercontent.com/894428/94992295-5df61980-0589-11eb-892b-c05bfba05f90.png)

I can implement fields `enabled-since`, `enabled-until`, `visible-since`, `visible-until` but 4 fields are IMO complicating problem configuration.

I suggest the following:
 1) The problem **will be visible** before `since` period
 2) Between `since` and `avail` will be problem active (as it is now)
 3) and finally after the `avail` period, problem **will be inactive** meaning visible but no submission will be allowed.

Example of since and avail:
![image](https://user-images.githubusercontent.com/894428/94992586-559ede00-058b-11eb-92cb-c21ad194665e.png)

**Comment by janhybs** [comment]
in `config`, there will be new date time field `deadline`

Each problem can be in one of the four states based on a current date:
1. `< since` = **disabled**
2. `>= since < avail` = **active**
3. `>= avail < deadline` = **active** (with warning)
4. `> deadline` =  **disabled**

**Comment by janhybs** [comment]
Implemented
