### ISSUE TITLE
Mathjax Latex alignment

### ISSUE THREAD

**Issue by Paulie14** [code-critic/cc.net#7]
I do not know why, but Mathjax does not break lines on CC web.
I am not able to print a matrix with `pmatrix` or set of equations with `align`.

```
$$\begin{pmatrix} 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ \end{pmatrix}$$

$$\begin{align*}
&x=0.5,&& n=20,\\
&x=5,&& n=20,\\
&x=20,&& n=100.
\end{align*}$$
```

Typora application also uses Mathjax a displays it correctly. Did not test it anywhere else.
It is not a big issue, I am currently using 
[https://codecogs.com/latex/eqneditor.php](https://codecogs.com/latex/eqneditor.php) instead.

**Comment by Paulie14** [comment]
Another LaTeX problem:
I am used to write integrals precisely with the small space in front of dx
```$$\int\limits_0^1 u'v' \,\mathrm{d}x$$```
but comma is displayed instead of the small space.
I did not test other spaces, e.g. `\;`.

**Comment by janhybs** [comment]
The issue lies with markdown, as it's uses the `\` for escaping. That means that every `\` need to be escaped by another one. 
```
$$\begin{pmatrix} 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ \end{pmatrix}$$

$$\begin{align*}
&x=0.5,&& n=20,\\
&x=5,&& n=20,\\
&x=20,&& n=100.
\end{align*}$$
```
will produce:

![image](https://user-images.githubusercontent.com/894428/97080607-e30aa680-15fc-11eb-80b7-8921e60b17e0.png)

```
$$\\begin{pmatrix} 1 & 1 & 1 & 1\\\\ 1 & 1 & 1 & 1\\\\ 1 & 1 & 1 & 1\\\\ 1 & 1 & 1 & 1\\\\ \\end{pmatrix}$$

$$\\begin{align*}
&x=0.5,&& n=20,\\\\
&x=5,&& n=20,\\\\
&x=20,&& n=100.
\\end{align*}$$

$$\\int\\limits_0^1 u'v' \\,\\mathrm{d}x$$
```

will produce:
![image](https://user-images.githubusercontent.com/894428/97080625-059cbf80-15fd-11eb-956a-61efd80e7fb3.png)


I can tweak the system and add extra  `\` automatically but globally it could cause problems, so solution for now is following:
everyting which is the following `math` fence, will be automatically escaped:

<pre><code>
```math
$$\begin{pmatrix} 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ 1 & 1 & 1 & 1\\ \end{pmatrix}$$
```
</code></pre>

![image](https://user-images.githubusercontent.com/894428/97080726-e3577180-15fd-11eb-8435-4de64bbd27c8.png)
